# DataFrame 데이터 변형하기
 
**기존 데이터를 변형하는 자잘한 기능들**
 
**중복된 값 제거하기**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.DataFrame({'k1': ['one']*3 + ['two']*4,
                  'k2': [1,1,2,3,3,4,4]})

In [3]:
df1

    k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

df1을 살펴보면 몇 군데 중복된 행이 포함되어 있다. df.duplicated() 함수를 실행하면, 중복된 행이 등장하는 부분이 True로, 그 외의 부분이 False로 구성된 Series 형태의 불리언 마스크를 얻을 수 있음. 
 
이렇게 얻은 불리언 마스크를 가지고 중복된 행들을 직접 처리해도 되고, 혹은 df.drop_duplicates() 함수를 사용하면 중복된 값이 제거된 새로운 DataFrame을 얻을 수 있다.

In [18]:
df1.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [5]:
# 중복값 제거
a = df1.drop_duplicates()
a

    k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

*df1에 새로운 열을 하나 추가*

In [7]:
df1['v1'] = np.arange(7)

In [8]:
df1

    k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

중복된 값이 없는 "v1" 열이 추가됨. 이 상태에서 특정 열의 값을 기준으로 하여 해당 열에서 중복된 값을 가지는 행들을 제거할 수도 있음

In [9]:
df1.drop_duplicates(['k1'])

    k1  k2  v1
0  one   1   0
3  two   3   3

In [30]:
df.drop_duplicates(['k1', 'k2'], keep ='last')

    k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

df.drop_duplicates() 함수에 keep 인자를 추가하였는데, 이는 중복된 행들 중 한 행만을 남기고 나머지를 제거하는 과정에서 맨 마지막에 등장한 것을 남길지, 맨 처음에 등장한 것을 남길지 결정하는 부분이다. "last" 값을 대입할 경우 맨 마지막, "first" 값을 대입할 경우 맨 처음 행을 남기게 된다.

**데이터 매핑하기 **

In [14]:
df2 = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 
                             'corned beef', 'Bacon', 'pastrami', 'honey ham',
                             'nova lox'],
                    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [15]:
df2

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

생성된 df2의 "food" 열에 몇 가지 값이 들어가 있는데, 이 "food" 열의 값들을 새로운 값으로 매핑하는 새로운 딕셔너리를 정의.

In [16]:
meat_to_animal = { 
    'bacon': 'pig', 
    'pulled pork': 'pig', 
    'pastrami': 'cow', 
    'corned beef': 'cow', 
    'honey ham': 'pig', 
    'nova lox': 'salmon'
}

이 meat_to_animal 딕셔너리에 명시된 규칙에 의거하여, "food" 열의 값들을 "pig", "cow", "salmon" 중 하나로 치환한 뒤 이들을 갖는 새로운 "animal" 열을 다음과 같이 추가할 수 있다.

In [17]:
df2["animal"] = df2["food"].apply(lambda x: meat_to_animal[x.lower()])
df2

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

: df2.apply() 함수를 사용하여, 기존 "food" 열에 포함된 각 문자열 값에 str.lower() 함수를 먼저 적용하여 모두 소문자로 변환한 뒤 이를 키로 갖는 meat_to_animal에서의 값을 반환하는 코드.

**값 치환하기 **

pandas에서 Series에 대해 제공하는 s.replace() 함수를 사용하면, Series 상의 특정 값을 다른 값으로 치환하는 작업을 유연하게 할 수 있음.

In [18]:
s = pd.Series([1., -999., 2., -999., -1000., 3.])

In [19]:
s

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

s.replace() 함수를 적용하여, 특정 값을 가지는 성분들을 모두 NaN으로 치환할 수 있다. 혹은 반대로, NaN을 모두 0으로 치환할 수 있다.

In [20]:
s2 = s.replace(-999, np.nan)

In [21]:
s2

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [22]:
s2.replace(np.nan, 0)

0       1.0
1       0.0
2       2.0
3       0.0
4   -1000.0
5       3.0
dtype: float64

** Categories(카테고리) 자료형 **
 
어떤 데이터셋에서 유한 가지 값들 중 하나를 가지는 열이 존재하는 경우가 많다. 예를 들어 고객의 성별을 나타내는 열에서 '남성'이면 "male", '여성'이면 "female" 값을 가지는 것이 대표적인 경우. 이러한 유형의 데이터를 '카테고리(category, 범주형)' 데이터라고 함.
 
이런 카테고리 데이터를 관리하기 위해, pandas에서는 'Categories'라는 특별한 자료형을 제공. Categories 자료형을 활용하면, 단순히 문자열 자료형으로 저장되어 있던 데이터를 대체함으로써 메모리 사용량을 줄일 수 있으며, 이에 대한 각종 통계 분석도 보다 간편하게 할 수 있다.
 
**Categories 열 생성하기**

In [45]:
df4 = pd.DataFrame({'id':[1,2,3,4,5,6],
                   'raw_grade': ['a','b','b','a','a','e']})

In [46]:
df4

   id raw_grade
0   1         a
1   2         b
2   3         b
3   4         a
4   5         a
5   6         e

df4의 "raw_grade" 열에는 'a', 'b', 'e' 등의 카테고리 값이 단순 문자열 형태로 저장되어 있다. 이를 Categories 자료형으로 치환한 새로운 "grade" 열을 다음과 같이 정의.

In [47]:
df4['grade'] = df4['raw_grade'].astype('category')
df4['grade']

0    a
1    b
2    b
3    a
4    a
5    e
Name: grade, dtype: category
Categories (3, object): [a, b, e]

df4["grade"]를 확인해보면 'Categories (3, object): [a, b, e]'라고 표시되는 것을 확인할 수 있는데, 이는 해당 열이 Categories 자료형의 Series라는 것이며, 이것이 'a', 'b', 'e'의 3가지 카테고리 값을 가질 수 있다는 것을 나타낸다.

In [48]:
# 현재 "grade" 열이 가질 수 있는 카테고리 값 확인

df4['grade'].cat.categories

Index(['a', 'b', 'e'], dtype='object')

In [49]:
# 새로운 카테고리를 포함하는 리스트 입력
df4["grade"].cat.categories = ["very bad", "good", "very good"]
df4

   id raw_grade      grade
0   1         a   very bad
1   2         b       good
2   3         b       good
3   4         a   very bad
4   5         a   very bad
5   6         e  very good

한편 기존 카테고리 값의 종류를 늘이거나 줄이는 것도 가능함. df4["grade"].cat.set_categories() 함수를 사용하여, 기존 카테고리 값에서 추가되거나 삭제된 것들을 리스트 형태의 인자로 명시하면 된다.

In [53]:
df4["grade"] = df4["grade"].cat.set_categories(["very bad", "bad", "medium", "good", "very good"])

Categories 자료형의 또 다른 특징은, 처음 정의할 때 부여한 순서에 따라 대소 관계를 가진다는 것. 다음과 같이 "grade" 열의 값을 기준으로 DataFrame을 정렬

In [54]:
df4.sort_values(by='grade')

   id raw_grade      grade
0   1         a   very bad
3   4         a   very bad
4   5         a   very bad
1   2         b       good
2   3         b       good
5   6         e  very good

**숫자 데이터의 카테고리화**
 
고객 데이터셋을 관리할 때 '연령'을 나타내는 열이 숫자 데이터로 구성되어 있었다고 하자. 이를 '청소년' -> '청년' -> '장년' -> '중년' 등과 같이 일정한 나이 기준으로 구간을 잘라서 카테고리 데이터로 변환하여 관리하면 좀 더 편리해지는 경우가 있다. 
pandas에서는 숫자 데이터를 빠르고 간편하게 카테고리화하는 기능을 제공함.

In [55]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

ages 리스트에 카테고리화 하고자 하는 숫자 데이터를, bins 리스트에 각 구간을 구분하는 숫자값을 명시함. 즉, 이렇게 하면 18세 초과 25세 이하, 25세 초과 35세 이하 등과 같이 총 4개의 구간을 정의. 
pd.cut() 함수를 사용, ages와 bins를 인자로 입력함으로써 ages 리스트의 각 성분들을 카테고리화 할 수 있다.

In [57]:
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

cats를 확인해보면 기존의 ages 리스트의 각 성분이 4가지 카테고리 값 중 하나로 대체된 결과물을 확인할 수 있다. cats.categories를 확인하면, 이 과정에서 사용된 카테고리 값들만을 직접 확인할수도 있다. 또 cats.codes를 확인하면, 기존 ages 리스트의 각 성분에 (0부터 시작하는 인덱스 형태로) 몇 번째 카테고리 값이 부여되었는지를 확인할 수도 있다. 
 
만약 "(18, 25]"와 같은 이름이 별로 보기 좋지 않다면, pd.cut() 함수를 실행할 때 labels 인자의 값을 입력함으로써 각 카테고리의 이름을 직접 명시할 수도 있다.

In [58]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [59]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [60]:
# 카테로리를 문자로 표현
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

만약 구간을 구분하는 기준값을 명시하는 것이 귀찮다면, pd.cut() 함수를 호출할 때 몇 개의 구간으로 나눌 것인지만 명시해주면 pandas에서 알아서 판단하여 길이가 일정한 구간을 정의하고 각 성분을 카테고리화한다. 이 때 precision 인자는 구간을 구분하는 기준값을 결정할 때 소수 몇 번째 자리까지 고려할지 결정.

In [77]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.75, 1.0], (0.51, 0.75], (0.51, 0.75], (0.51, 0.75], (0.015, 0.26], ..., (0.75, 1.0], (0.015, 0.26], (0.26, 0.51], (0.26, 0.51], (0.015, 0.26]]
Length: 20
Categories (4, interval[float64]): [(0.015, 0.26] < (0.26, 0.51] < (0.51, 0.75] < (0.75, 1.0]]

한편 pd.qcut()이라는 함수도 있는데, 이는 지정한 갯수만큼의 구간을 정의하되, 분위수를 구분값으로 한다.

In [80]:
data2 = np.random.randn(1000)
cats = pd.qcut(data2, 4)
cats

[(-3.401, -0.645], (0.00175, 0.607], (0.00175, 0.607], (-0.645, 0.00175], (-0.645, 0.00175], ..., (0.00175, 0.607], (0.607, 3.202], (0.607, 3.202], (-0.645, 0.00175], (-0.645, 0.00175]]
Length: 1000
Categories (4, interval[float64]): [(-3.401, -0.645] < (-0.645, 0.00175] < (0.00175, 0.607] < (0.607, 3.202]]